# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Thu Apr 12 00:55:25 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1508, 828)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.viewTabs = QtGui.QTabWidget(self.splitter)
        self.viewTabs.setMovable(True)
        self.viewTabs.setObjectName("viewTabs")
        self.openGlTab = QtGui.QWidget()
        self.openGlTab.setObjectName("openGlTab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.openGlTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtGui.QLabel(self.openGlTab)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.setView = QtGui.QComboBox(self.openGlTab)
        self.setView.setObjectName("setView")
        self.setView.addItem("")
        self.setView.setItemText(0, "")
        self.setView.addItem("")
        self.setView.addItem("")
        self.setView.addItem("")
        self.setView.addItem("")
        self.setView.addItem("")
        self.setView.addItem("")
        self.setView.addItem("")
        self.setView.addItem("")
        self.setView.addItem("")
        self.setView.addItem("")
        self.setView.addItem("")
        self.setView.addItem("")
        self.setView.addItem("")
        self.setView.addItem("")
        self.horizontalLayout_2.addWidget(self.setView)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.automate = QtGui.QPushButton(self.openGlTab)
        self.automate.setObjectName("automate")
        self.horizontalLayout_2.addWidget(self.automate)
        self.loadModel = QtGui.QPushButton(self.openGlTab)
        self.loadModel.setObjectName("loadModel")
        self.horizontalLayout_2.addWidget(self.loadModel)
        self.loadAtlas = QtGui.QPushButton(self.openGlTab)
        self.loadAtlas.setObjectName("loadAtlas")
        self.horizontalLayout_2.addWidget(self.loadAtlas)
        self.defaultScene = QtGui.QPushButton(self.openGlTab)
        self.defaultScene.setObjectName("defaultScene")
        self.horizontalLayout_2.addWidget(self.defaultScene)
        self.clearScene = QtGui.QPushButton(self.openGlTab)
        self.clearScene.setObjectName("clearScene")
        self.horizontalLayout_2.addWidget(self.clearScene)
        self.GrabScreen = QtGui.QPushButton(self.openGlTab)
        self.GrabScreen.setObjectName("GrabScreen")
        self.horizontalLayout_2.addWidget(self.GrabScreen)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.viewTabs.addTab(self.openGlTab, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_74 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.horizontalLayout_10.addWidget(self.label_74)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.copyTable = QtGui.QPushButton(self.tab_7)
        self.copyTable.setObjectName("copyTable")
        self.horizontalLayout_10.addWidget(self.copyTable)
        self.saveCSV = QtGui.QPushButton(self.tab_7)
        self.saveCSV.setObjectName("saveCSV")
        self.horizontalLayout_10.addWidget(self.saveCSV)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.nmTable = QtGui.QTableWidget(self.tab_7)
        self.nmTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.nmTable.setObjectName("nmTable")
        self.nmTable.setColumnCount(0)
        self.nmTable.setRowCount(0)
        self.verticalLayout_9.addWidget(self.nmTable)
        self.viewTabs.addTab(self.tab_7, "")
        self.verticalLayout_6.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1508, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.dockItemList = QtGui.QDockWidget(MainWindow)
        self.dockItemList.setFloating(False)
        self.dockItemList.setFeatures(QtGui.QDockWidget.DockWidgetFloatable | QtGui.QDockWidget.DockWidgetMovable)
        self.dockItemList.setObjectName("dockItemList")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.itemTreeList = QtGui.QTreeWidget(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemTreeList.sizePolicy().hasHeightForWidth())
        self.itemTreeList.setSizePolicy(sizePolicy)
        self.itemTreeList.setToolTip("")
        self.itemTreeList.setColumnCount(1)
        self.itemTreeList.setObjectName("itemTreeList")
        self.itemTreeList.headerItem().setText(0, "1")
        self.itemTreeList.header().setVisible(False)
        self.gridLayout.addWidget(self.itemTreeList, 0, 0, 1, 1)
        self.dockItemList.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockItemList)
        self.dockCamera = QtGui.QDockWidget(MainWindow)
        self.dockCamera.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockCamera.setObjectName("dockCamera")
        self.dockWidgetContents_8 = QtGui.QWidget()
        self.dockWidgetContents_8.setObjectName("dockWidgetContents_8")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.dockWidgetContents_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.camUpdate = QtGui.QPushButton(self.dockWidgetContents_8)
        self.camUpdate.setObjectName("camUpdate")
        self.verticalLayout_8.addWidget(self.camUpdate)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_39 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_39.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_10.addWidget(self.label_39, 2, 0, 1, 1)
        self.label_40 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_40.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_10.addWidget(self.label_40, 3, 0, 1, 1)
        self.label_41 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_41.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_10.addWidget(self.label_41, 4, 0, 1, 1)
        self.camXPos = QtGui.QDoubleSpinBox(self.dockWidgetContents_8)
        self.camXPos.setEnabled(True)
        self.camXPos.setWrapping(False)
        self.camXPos.setReadOnly(False)
        self.camXPos.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.camXPos.setDecimals(10)
        self.camXPos.setMinimum(-1000000.0)
        self.camXPos.setMaximum(1000000.0)
        self.camXPos.setObjectName("camXPos")
        self.gridLayout_10.addWidget(self.camXPos, 2, 1, 1, 1)
        self.camYPos = QtGui.QDoubleSpinBox(self.dockWidgetContents_8)
        self.camYPos.setEnabled(True)
        self.camYPos.setReadOnly(False)
        self.camYPos.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.camYPos.setDecimals(10)
        self.camYPos.setMinimum(-1000000.0)
        self.camYPos.setMaximum(1000000.0)
        self.camYPos.setObjectName("camYPos")
        self.gridLayout_10.addWidget(self.camYPos, 3, 1, 1, 1)
        self.camZPos = QtGui.QDoubleSpinBox(self.dockWidgetContents_8)
        self.camZPos.setEnabled(True)
        self.camZPos.setReadOnly(False)
        self.camZPos.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.camZPos.setDecimals(10)
        self.camZPos.setMinimum(-1000000.0)
        self.camZPos.setMaximum(1000000.0)
        self.camZPos.setObjectName("camZPos")
        self.gridLayout_10.addWidget(self.camZPos, 4, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_42.setObjectName("label_42")
        self.gridLayout_10.addWidget(self.label_42, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem2, 2, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_10)
        self.line_9 = QtGui.QFrame(self.dockWidgetContents_8)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_8.addWidget(self.line_9)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_43 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_43.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_11.addWidget(self.label_43, 1, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_44.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_11.addWidget(self.label_44, 2, 0, 1, 1)
        self.label_45 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_45.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_11.addWidget(self.label_45, 3, 0, 1, 1)
        self.camXLookAt = QtGui.QDoubleSpinBox(self.dockWidgetContents_8)
        self.camXLookAt.setEnabled(True)
        self.camXLookAt.setWrapping(False)
        self.camXLookAt.setReadOnly(False)
        self.camXLookAt.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.camXLookAt.setDecimals(10)
        self.camXLookAt.setMinimum(-1000000.0)
        self.camXLookAt.setMaximum(1000000.0)
        self.camXLookAt.setObjectName("camXLookAt")
        self.gridLayout_11.addWidget(self.camXLookAt, 1, 1, 1, 1)
        self.camYLookAt = QtGui.QDoubleSpinBox(self.dockWidgetContents_8)
        self.camYLookAt.setEnabled(True)
        self.camYLookAt.setReadOnly(False)
        self.camYLookAt.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.camYLookAt.setDecimals(10)
        self.camYLookAt.setMinimum(-1000000.0)
        self.camYLookAt.setMaximum(1000000.0)
        self.camYLookAt.setObjectName("camYLookAt")
        self.gridLayout_11.addWidget(self.camYLookAt, 2, 1, 1, 1)
        self.camZLookAt = QtGui.QDoubleSpinBox(self.dockWidgetContents_8)
        self.camZLookAt.setEnabled(True)
        self.camZLookAt.setReadOnly(False)
        self.camZLookAt.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.camZLookAt.setDecimals(10)
        self.camZLookAt.setMinimum(-1000000.0)
        self.camZLookAt.setMaximum(1000000.0)
        self.camZLookAt.setObjectName("camZLookAt")
        self.gridLayout_11.addWidget(self.camZLookAt, 3, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_46.setObjectName("label_46")
        self.gridLayout_11.addWidget(self.label_46, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 1, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_11)
        self.line_10 = QtGui.QFrame(self.dockWidgetContents_8)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_8.addWidget(self.line_10)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_47 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_47.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_12.addWidget(self.label_47, 1, 0, 1, 1)
        self.label_48 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_48.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_12.addWidget(self.label_48, 2, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_49.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout_12.addWidget(self.label_49, 3, 0, 1, 1)
        self.camXUp = QtGui.QDoubleSpinBox(self.dockWidgetContents_8)
        self.camXUp.setEnabled(True)
        self.camXUp.setWrapping(False)
        self.camXUp.setReadOnly(False)
        self.camXUp.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.camXUp.setDecimals(10)
        self.camXUp.setMinimum(-1000000.0)
        self.camXUp.setMaximum(1000000.0)
        self.camXUp.setObjectName("camXUp")
        self.gridLayout_12.addWidget(self.camXUp, 1, 1, 1, 1)
        self.camYUp = QtGui.QDoubleSpinBox(self.dockWidgetContents_8)
        self.camYUp.setEnabled(True)
        self.camYUp.setReadOnly(False)
        self.camYUp.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.camYUp.setDecimals(10)
        self.camYUp.setMinimum(-1000000.0)
        self.camYUp.setMaximum(1000000.0)
        self.camYUp.setObjectName("camYUp")
        self.gridLayout_12.addWidget(self.camYUp, 2, 1, 1, 1)
        self.camZUp = QtGui.QDoubleSpinBox(self.dockWidgetContents_8)
        self.camZUp.setEnabled(True)
        self.camZUp.setReadOnly(False)
        self.camZUp.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.camZUp.setDecimals(10)
        self.camZUp.setMinimum(-1000000.0)
        self.camZUp.setMaximum(1000000.0)
        self.camZUp.setObjectName("camZUp")
        self.gridLayout_12.addWidget(self.camZUp, 3, 1, 1, 1)
        self.label_50 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_50.setObjectName("label_50")
        self.gridLayout_12.addWidget(self.label_50, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem4, 1, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_12)
        self.line_8 = QtGui.QFrame(self.dockWidgetContents_8)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_8.addWidget(self.line_8)
        self.label_59 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_8.addWidget(self.label_59)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_55 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_55.setObjectName("label_55")
        self.gridLayout_13.addWidget(self.label_55, 0, 0, 1, 1)
        self.label_56 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_56.setObjectName("label_56")
        self.gridLayout_13.addWidget(self.label_56, 1, 0, 1, 1)
        self.label_57 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_57.setObjectName("label_57")
        self.gridLayout_13.addWidget(self.label_57, 2, 0, 1, 1)
        self.camQuatW = QtGui.QDoubleSpinBox(self.dockWidgetContents_8)
        self.camQuatW.setReadOnly(False)
        self.camQuatW.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.camQuatW.setDecimals(10)
        self.camQuatW.setMinimum(-1000000.0)
        self.camQuatW.setMaximum(1000000.0)
        self.camQuatW.setObjectName("camQuatW")
        self.gridLayout_13.addWidget(self.camQuatW, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem5, 0, 2, 1, 1)
        self.camQuatX = QtGui.QDoubleSpinBox(self.dockWidgetContents_8)
        self.camQuatX.setReadOnly(False)
        self.camQuatX.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.camQuatX.setDecimals(10)
        self.camQuatX.setMinimum(-1000000.0)
        self.camQuatX.setMaximum(1000000.0)
        self.camQuatX.setObjectName("camQuatX")
        self.gridLayout_13.addWidget(self.camQuatX, 1, 1, 1, 1)
        self.camQuatY = QtGui.QDoubleSpinBox(self.dockWidgetContents_8)
        self.camQuatY.setReadOnly(False)
        self.camQuatY.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.camQuatY.setDecimals(10)
        self.camQuatY.setMinimum(-1000000.0)
        self.camQuatY.setMaximum(1000000.0)
        self.camQuatY.setObjectName("camQuatY")
        self.gridLayout_13.addWidget(self.camQuatY, 2, 1, 1, 1)
        self.camQuatZ = QtGui.QDoubleSpinBox(self.dockWidgetContents_8)
        self.camQuatZ.setReadOnly(False)
        self.camQuatZ.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.camQuatZ.setDecimals(10)
        self.camQuatZ.setMinimum(-1000000.0)
        self.camQuatZ.setMaximum(1000000.0)
        self.camQuatZ.setObjectName("camQuatZ")
        self.gridLayout_13.addWidget(self.camQuatZ, 3, 1, 1, 1)
        self.label_58 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_58.setObjectName("label_58")
        self.gridLayout_13.addWidget(self.label_58, 3, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_13)
        self.line_11 = QtGui.QFrame(self.dockWidgetContents_8)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_8.addWidget(self.line_11)
        self.camFunction = QtGui.QLineEdit(self.dockWidgetContents_8)
        self.camFunction.setObjectName("camFunction")
        self.verticalLayout_8.addWidget(self.camFunction)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.dockCamera.setWidget(self.dockWidgetContents_8)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockCamera)
        self.dockLights = QtGui.QDockWidget(MainWindow)
        self.dockLights.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockLights.setObjectName("dockLights")
        self.dockWidgetContents_9 = QtGui.QWidget()
        self.dockWidgetContents_9.setObjectName("dockWidgetContents_9")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.dockWidgetContents_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.dockWidgetContents_9)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lightNum = QtGui.QSpinBox(self.dockWidgetContents_9)
        self.lightNum.setMaximum(7)
        self.lightNum.setObjectName("lightNum")
        self.horizontalLayout_3.addWidget(self.lightNum)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.lightEnable = QtGui.QCheckBox(self.dockWidgetContents_9)
        self.lightEnable.setObjectName("lightEnable")
        self.verticalLayout_7.addWidget(self.lightEnable)
        self.line = QtGui.QFrame(self.dockWidgetContents_9)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_9)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.dockWidgetContents_9)
        self.label_5.setEnabled(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.chooseDiffuseColorCam = QtGui.QPushButton(self.dockWidgetContents_9)
        self.chooseDiffuseColorCam.setText("")
        self.chooseDiffuseColorCam.setObjectName("chooseDiffuseColorCam")
        self.gridLayout_2.addWidget(self.chooseDiffuseColorCam, 2, 1, 1, 1)
        self.chooseEmissiveColorCam = QtGui.QPushButton(self.dockWidgetContents_9)
        self.chooseEmissiveColorCam.setEnabled(False)
        self.chooseEmissiveColorCam.setText("")
        self.chooseEmissiveColorCam.setObjectName("chooseEmissiveColorCam")
        self.gridLayout_2.addWidget(self.chooseEmissiveColorCam, 4, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 1, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.dockWidgetContents_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.chooseSpecularColorCam = QtGui.QPushButton(self.dockWidgetContents_9)
        self.chooseSpecularColorCam.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseSpecularColorCam.sizePolicy().hasHeightForWidth())
        self.chooseSpecularColorCam.setSizePolicy(sizePolicy)
        self.chooseSpecularColorCam.setText("")
        self.chooseSpecularColorCam.setObjectName("chooseSpecularColorCam")
        self.gridLayout_2.addWidget(self.chooseSpecularColorCam, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_9)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_9)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.chooseAmbientColorCam = QtGui.QPushButton(self.dockWidgetContents_9)
        self.chooseAmbientColorCam.setText("")
        self.chooseAmbientColorCam.setObjectName("chooseAmbientColorCam")
        self.gridLayout_2.addWidget(self.chooseAmbientColorCam, 1, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.line_2 = QtGui.QFrame(self.dockWidgetContents_9)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_9)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.dockWidgetContents_9)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.dockWidgetContents_9)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.lightXPos = QtGui.QDoubleSpinBox(self.dockWidgetContents_9)
        self.lightXPos.setMinimum(-1000000.0)
        self.lightXPos.setMaximum(1000000.0)
        self.lightXPos.setObjectName("lightXPos")
        self.gridLayout_3.addWidget(self.lightXPos, 4, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 4, 2, 1, 1)
        self.lightYPos = QtGui.QDoubleSpinBox(self.dockWidgetContents_9)
        self.lightYPos.setMinimum(-1000000.0)
        self.lightYPos.setMaximum(1000000.0)
        self.lightYPos.setObjectName("lightYPos")
        self.gridLayout_3.addWidget(self.lightYPos, 5, 1, 1, 1)
        self.lightZPos = QtGui.QDoubleSpinBox(self.dockWidgetContents_9)
        self.lightZPos.setMinimum(-1000000.0)
        self.lightZPos.setMaximum(1000000.0)
        self.lightZPos.setObjectName("lightZPos")
        self.gridLayout_3.addWidget(self.lightZPos, 6, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.dockWidgetContents_9)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.directionalLight = QtGui.QCheckBox(self.dockWidgetContents_9)
        self.directionalLight.setChecked(True)
        self.directionalLight.setObjectName("directionalLight")
        self.verticalLayout_7.addWidget(self.directionalLight)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem10)
        self.dockLights.setWidget(self.dockWidgetContents_9)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockLights)
        self.dockModel = QtGui.QDockWidget(MainWindow)
        self.dockModel.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockModel.setObjectName("dockModel")
        self.dockWidgetContents_10 = QtGui.QWidget()
        self.dockWidgetContents_10.setObjectName("dockWidgetContents_10")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.modelName = QtGui.QLineEdit(self.dockWidgetContents_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.modelName.setFont(font)
        self.modelName.setObjectName("modelName")
        self.verticalLayout.addWidget(self.modelName)
        self.modelVisible = QtGui.QCheckBox(self.dockWidgetContents_10)
        self.modelVisible.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.modelVisible.setFont(font)
        self.modelVisible.setObjectName("modelVisible")
        self.verticalLayout.addWidget(self.modelVisible)
        self.enableColorDrivenModelsCheckBox = QtGui.QCheckBox(self.dockWidgetContents_10)
        self.enableColorDrivenModelsCheckBox.setEnabled(True)
        self.enableColorDrivenModelsCheckBox.setChecked(True)
        self.enableColorDrivenModelsCheckBox.setObjectName("enableColorDrivenModelsCheckBox")
        self.verticalLayout.addWidget(self.enableColorDrivenModelsCheckBox)
        self.line_3 = QtGui.QFrame(self.dockWidgetContents_10)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_18 = QtGui.QLabel(self.dockWidgetContents_10)
        self.label_18.setEnabled(True)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.dockWidgetContents_10)
        self.label_23.setEnabled(True)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 4, 0, 1, 1)
        self.chooseDiffuseColorMat = QtGui.QPushButton(self.dockWidgetContents_10)
        self.chooseDiffuseColorMat.setEnabled(False)
        self.chooseDiffuseColorMat.setText("")
        self.chooseDiffuseColorMat.setCheckable(False)
        self.chooseDiffuseColorMat.setChecked(False)
        self.chooseDiffuseColorMat.setAutoDefault(False)
        self.chooseDiffuseColorMat.setDefault(False)
        self.chooseDiffuseColorMat.setFlat(False)
        self.chooseDiffuseColorMat.setObjectName("chooseDiffuseColorMat")
        self.gridLayout_6.addWidget(self.chooseDiffuseColorMat, 2, 1, 1, 1)
        self.chooseEmissiveColorMat = QtGui.QPushButton(self.dockWidgetContents_10)
        self.chooseEmissiveColorMat.setEnabled(False)
        self.chooseEmissiveColorMat.setText("")
        self.chooseEmissiveColorMat.setObjectName("chooseEmissiveColorMat")
        self.gridLayout_6.addWidget(self.chooseEmissiveColorMat, 4, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem11, 1, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.dockWidgetContents_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 0, 0, 1, 1)
        self.chooseSpecularColorMat = QtGui.QPushButton(self.dockWidgetContents_10)
        self.chooseSpecularColorMat.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseSpecularColorMat.sizePolicy().hasHeightForWidth())
        self.chooseSpecularColorMat.setSizePolicy(sizePolicy)
        self.chooseSpecularColorMat.setText("")
        self.chooseSpecularColorMat.setObjectName("chooseSpecularColorMat")
        self.gridLayout_6.addWidget(self.chooseSpecularColorMat, 3, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.dockWidgetContents_10)
        self.label_17.setEnabled(True)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 3, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.dockWidgetContents_10)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 1, 0, 1, 1)
        self.chooseAmbientColorMat = QtGui.QPushButton(self.dockWidgetContents_10)
        self.chooseAmbientColorMat.setEnabled(False)
        self.chooseAmbientColorMat.setText("")
        self.chooseAmbientColorMat.setObjectName("chooseAmbientColorMat")
        self.gridLayout_6.addWidget(self.chooseAmbientColorMat, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_32 = QtGui.QLabel(self.dockWidgetContents_10)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_8.addWidget(self.label_32)
        self.modelAlpha = QtGui.QSlider(self.dockWidgetContents_10)
        self.modelAlpha.setMaximum(255)
        self.modelAlpha.setOrientation(QtCore.Qt.Horizontal)
        self.modelAlpha.setObjectName("modelAlpha")
        self.horizontalLayout_8.addWidget(self.modelAlpha)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_25 = QtGui.QLabel(self.dockWidgetContents_10)
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.dockWidgetContents_10)
        self.label_26.setObjectName("label_26")
        self.gridLayout_7.addWidget(self.label_26, 1, 2, 1, 1)
        self.matShinySlider = QtGui.QSlider(self.dockWidgetContents_10)
        self.matShinySlider.setEnabled(False)
        self.matShinySlider.setMaximum(128)
        self.matShinySlider.setProperty("value", 128)
        self.matShinySlider.setOrientation(QtCore.Qt.Horizontal)
        self.matShinySlider.setObjectName("matShinySlider")
        self.gridLayout_7.addWidget(self.matShinySlider, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_27 = QtGui.QLabel(self.dockWidgetContents_10)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout.addWidget(self.label_27)
        self.matShinySpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents_10)
        self.matShinySpinBox.setEnabled(False)
        self.matShinySpinBox.setMaximum(128.0)
        self.matShinySpinBox.setProperty("value", 128.0)
        self.matShinySpinBox.setObjectName("matShinySpinBox")
        self.horizontalLayout.addWidget(self.matShinySpinBox)
        self.gridLayout_7.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.invertNormals = QtGui.QPushButton(self.dockWidgetContents_10)
        self.invertNormals.setObjectName("invertNormals")
        self.verticalLayout.addWidget(self.invertNormals)
        self.saveModel = QtGui.QPushButton(self.dockWidgetContents_10)
        self.saveModel.setObjectName("saveModel")
        self.verticalLayout.addWidget(self.saveModel)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_75 = QtGui.QLabel(self.dockWidgetContents_10)
        self.label_75.setObjectName("label_75")
        self.horizontalLayout_11.addWidget(self.label_75)
        self.pointSize = QtGui.QDoubleSpinBox(self.dockWidgetContents_10)
        self.pointSize.setDecimals(3)
        self.pointSize.setSingleStep(0.1)
        self.pointSize.setProperty("value", 1.0)
        self.pointSize.setObjectName("pointSize")
        self.horizontalLayout_11.addWidget(self.pointSize)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.dockModel.setWidget(self.dockWidgetContents_10)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockModel)
        self.dockJoint = QtGui.QDockWidget(MainWindow)
        self.dockJoint.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockJoint.setObjectName("dockJoint")
        self.dockWidgetContents_11 = QtGui.QWidget()
        self.dockWidgetContents_11.setObjectName("dockWidgetContents_11")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_11)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.jointName = QtGui.QLineEdit(self.dockWidgetContents_11)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.jointName.setFont(font)
        self.jointName.setObjectName("jointName")
        self.verticalLayout_2.addWidget(self.jointName)
        self.line_4 = QtGui.QFrame(self.dockWidgetContents_11)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_28 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_4.addWidget(self.label_28)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.label_19 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.rotationOrder = QtGui.QComboBox(self.dockWidgetContents_11)
        self.rotationOrder.setEnabled(False)
        self.rotationOrder.setObjectName("rotationOrder")
        self.rotationOrder.addItem("")
        self.rotationOrder.addItem("")
        self.rotationOrder.addItem("")
        self.rotationOrder.addItem("")
        self.rotationOrder.addItem("")
        self.rotationOrder.addItem("")
        self.horizontalLayout_4.addWidget(self.rotationOrder)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.sphericalCoord = QtGui.QCheckBox(self.dockWidgetContents_11)
        self.sphericalCoord.setChecked(True)
        self.sphericalCoord.setObjectName("sphericalCoord")
        self.verticalLayout_2.addWidget(self.sphericalCoord)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.xAxisLabel = QtGui.QLabel(self.dockWidgetContents_11)
        self.xAxisLabel.setObjectName("xAxisLabel")
        self.gridLayout_8.addWidget(self.xAxisLabel, 1, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 0, 0, 1, 1)
        self.jointXRotSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointXRotSpinBox.setEnabled(False)
        self.jointXRotSpinBox.setMinimum(-90.0)
        self.jointXRotSpinBox.setMaximum(90.0)
        self.jointXRotSpinBox.setSingleStep(15.0)
        self.jointXRotSpinBox.setObjectName("jointXRotSpinBox")
        self.gridLayout_8.addWidget(self.jointXRotSpinBox, 1, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 0, 2, 1, 1)
        self.zAxisLabel = QtGui.QLabel(self.dockWidgetContents_11)
        self.zAxisLabel.setObjectName("zAxisLabel")
        self.gridLayout_8.addWidget(self.zAxisLabel, 3, 0, 1, 1)
        self.yAxisLabel = QtGui.QLabel(self.dockWidgetContents_11)
        self.yAxisLabel.setObjectName("yAxisLabel")
        self.gridLayout_8.addWidget(self.yAxisLabel, 2, 0, 1, 1)
        self.jointYRotSlider = QtGui.QSlider(self.dockWidgetContents_11)
        self.jointYRotSlider.setEnabled(False)
        self.jointYRotSlider.setMaximum(360)
        self.jointYRotSlider.setOrientation(QtCore.Qt.Horizontal)
        self.jointYRotSlider.setObjectName("jointYRotSlider")
        self.gridLayout_8.addWidget(self.jointYRotSlider, 2, 1, 1, 1)
        self.jointZRotSlider = QtGui.QSlider(self.dockWidgetContents_11)
        self.jointZRotSlider.setEnabled(False)
        self.jointZRotSlider.setMaximum(360)
        self.jointZRotSlider.setOrientation(QtCore.Qt.Horizontal)
        self.jointZRotSlider.setObjectName("jointZRotSlider")
        self.gridLayout_8.addWidget(self.jointZRotSlider, 3, 1, 1, 1)
        self.jointYRotSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointYRotSpinBox.setEnabled(False)
        self.jointYRotSpinBox.setMaximum(360.0)
        self.jointYRotSpinBox.setSingleStep(15.0)
        self.jointYRotSpinBox.setObjectName("jointYRotSpinBox")
        self.gridLayout_8.addWidget(self.jointYRotSpinBox, 2, 2, 1, 1)
        self.jointZRotSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointZRotSpinBox.setEnabled(False)
        self.jointZRotSpinBox.setMaximum(360.0)
        self.jointZRotSpinBox.setSingleStep(15.0)
        self.jointZRotSpinBox.setObjectName("jointZRotSpinBox")
        self.gridLayout_8.addWidget(self.jointZRotSpinBox, 3, 2, 1, 1)
        self.jointXRotSlider = QtGui.QSlider(self.dockWidgetContents_11)
        self.jointXRotSlider.setEnabled(False)
        self.jointXRotSlider.setMinimum(-90)
        self.jointXRotSlider.setMaximum(90)
        self.jointXRotSlider.setOrientation(QtCore.Qt.Horizontal)
        self.jointXRotSlider.setObjectName("jointXRotSlider")
        self.gridLayout_8.addWidget(self.jointXRotSlider, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_8)
        self.line_5 = QtGui.QFrame(self.dockWidgetContents_11)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_51 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_51.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout_14.addWidget(self.label_51, 3, 0, 1, 1)
        self.label_52 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_52.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName("label_52")
        self.gridLayout_14.addWidget(self.label_52, 4, 0, 1, 1)
        self.label_53 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_53.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_14.addWidget(self.label_53, 5, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem14, 3, 2, 1, 1)
        self.jointScaleX = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointScaleX.setDecimals(4)
        self.jointScaleX.setMinimum(0.0001)
        self.jointScaleX.setMaximum(100.0)
        self.jointScaleX.setSingleStep(0.1)
        self.jointScaleX.setProperty("value", 1.0)
        self.jointScaleX.setObjectName("jointScaleX")
        self.gridLayout_14.addWidget(self.jointScaleX, 3, 1, 1, 1)
        self.label_60 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_60.setObjectName("label_60")
        self.gridLayout_14.addWidget(self.label_60, 0, 1, 1, 1)
        self.jointScaleY = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointScaleY.setDecimals(4)
        self.jointScaleY.setMinimum(0.0001)
        self.jointScaleY.setMaximum(100.0)
        self.jointScaleY.setSingleStep(0.1)
        self.jointScaleY.setProperty("value", 1.0)
        self.jointScaleY.setObjectName("jointScaleY")
        self.gridLayout_14.addWidget(self.jointScaleY, 4, 1, 1, 1)
        self.jointScaleZ = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointScaleZ.setDecimals(4)
        self.jointScaleZ.setMinimum(0.0001)
        self.jointScaleZ.setMaximum(100.0)
        self.jointScaleZ.setSingleStep(0.1)
        self.jointScaleZ.setProperty("value", 1.0)
        self.jointScaleZ.setObjectName("jointScaleZ")
        self.gridLayout_14.addWidget(self.jointScaleZ, 5, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_29.setObjectName("label_29")
        self.gridLayout_14.addWidget(self.label_29, 2, 0, 1, 1)
        self.jointScaleXYZ = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointScaleXYZ.setDecimals(4)
        self.jointScaleXYZ.setMinimum(0.0001)
        self.jointScaleXYZ.setMaximum(100.0)
        self.jointScaleXYZ.setSingleStep(0.1)
        self.jointScaleXYZ.setProperty("value", 1.0)
        self.jointScaleXYZ.setObjectName("jointScaleXYZ")
        self.gridLayout_14.addWidget(self.jointScaleXYZ, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_14)
        self.line_7 = QtGui.QFrame(self.dockWidgetContents_11)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_2.addWidget(self.line_7)
        self.label_34 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_34.setToolTip("")
        self.label_34.setObjectName("label_34")
        self.verticalLayout_2.addWidget(self.label_34)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_35 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_35.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_9.addWidget(self.label_35, 1, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_36.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_9.addWidget(self.label_36, 2, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_37.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_9.addWidget(self.label_37, 3, 0, 1, 1)
        self.jointXPos = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointXPos.setEnabled(True)
        self.jointXPos.setWrapping(False)
        self.jointXPos.setReadOnly(True)
        self.jointXPos.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.jointXPos.setMinimum(-1000000.0)
        self.jointXPos.setMaximum(1000000.0)
        self.jointXPos.setObjectName("jointXPos")
        self.gridLayout_9.addWidget(self.jointXPos, 1, 1, 1, 1)
        self.jointYPos = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointYPos.setEnabled(True)
        self.jointYPos.setReadOnly(True)
        self.jointYPos.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.jointYPos.setMinimum(-1000000.0)
        self.jointYPos.setMaximum(1000000.0)
        self.jointYPos.setObjectName("jointYPos")
        self.gridLayout_9.addWidget(self.jointYPos, 2, 1, 1, 1)
        self.jointZPos = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointZPos.setEnabled(True)
        self.jointZPos.setReadOnly(True)
        self.jointZPos.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.jointZPos.setMinimum(-1000000.0)
        self.jointZPos.setMaximum(1000000.0)
        self.jointZPos.setObjectName("jointZPos")
        self.gridLayout_9.addWidget(self.jointZPos, 3, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_33.setObjectName("label_33")
        self.gridLayout_9.addWidget(self.label_33, 0, 1, 1, 1)
        self.jointXPosStep = QtGui.QPushButton(self.dockWidgetContents_11)
        self.jointXPosStep.setObjectName("jointXPosStep")
        self.gridLayout_9.addWidget(self.jointXPosStep, 1, 3, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem15, 1, 4, 1, 1)
        self.jointXPosStepSize = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointXPosStepSize.setMinimum(-1000.0)
        self.jointXPosStepSize.setMaximum(1000.0)
        self.jointXPosStepSize.setObjectName("jointXPosStepSize")
        self.gridLayout_9.addWidget(self.jointXPosStepSize, 1, 2, 1, 1)
        self.label_38 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_38.setObjectName("label_38")
        self.gridLayout_9.addWidget(self.label_38, 0, 2, 1, 1)
        self.jointYPosStep = QtGui.QPushButton(self.dockWidgetContents_11)
        self.jointYPosStep.setObjectName("jointYPosStep")
        self.gridLayout_9.addWidget(self.jointYPosStep, 2, 3, 1, 1)
        self.jointZPosStep = QtGui.QPushButton(self.dockWidgetContents_11)
        self.jointZPosStep.setObjectName("jointZPosStep")
        self.gridLayout_9.addWidget(self.jointZPosStep, 3, 3, 1, 1)
        self.jointYPosStepSize = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointYPosStepSize.setMinimum(-1000.0)
        self.jointYPosStepSize.setMaximum(1000.0)
        self.jointYPosStepSize.setObjectName("jointYPosStepSize")
        self.gridLayout_9.addWidget(self.jointYPosStepSize, 2, 2, 1, 1)
        self.jointZPosStepSize = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointZPosStepSize.setMinimum(-1000.0)
        self.jointZPosStepSize.setMaximum(1000.0)
        self.jointZPosStepSize.setObjectName("jointZPosStepSize")
        self.gridLayout_9.addWidget(self.jointZPosStepSize, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_9)
        self.line_6 = QtGui.QFrame(self.dockWidgetContents_11)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_2.addWidget(self.line_6)
        self.label_12 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_13 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 2, 0, 1, 1)
        self.jointQuatW = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointQuatW.setReadOnly(True)
        self.jointQuatW.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.jointQuatW.setMinimum(-1000000.0)
        self.jointQuatW.setMaximum(1000000.0)
        self.jointQuatW.setObjectName("jointQuatW")
        self.gridLayout_4.addWidget(self.jointQuatW, 0, 1, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem16, 0, 2, 1, 1)
        self.jointQuatX = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointQuatX.setReadOnly(True)
        self.jointQuatX.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.jointQuatX.setMinimum(-1000000.0)
        self.jointQuatX.setMaximum(1000000.0)
        self.jointQuatX.setObjectName("jointQuatX")
        self.gridLayout_4.addWidget(self.jointQuatX, 1, 1, 1, 1)
        self.jointQuatY = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointQuatY.setReadOnly(True)
        self.jointQuatY.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.jointQuatY.setMinimum(-1000000.0)
        self.jointQuatY.setMaximum(1000000.0)
        self.jointQuatY.setObjectName("jointQuatY")
        self.gridLayout_4.addWidget(self.jointQuatY, 2, 1, 1, 1)
        self.jointQuatZ = QtGui.QDoubleSpinBox(self.dockWidgetContents_11)
        self.jointQuatZ.setReadOnly(True)
        self.jointQuatZ.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.jointQuatZ.setMinimum(-1000000.0)
        self.jointQuatZ.setMaximum(1000000.0)
        self.jointQuatZ.setObjectName("jointQuatZ")
        self.gridLayout_4.addWidget(self.jointQuatZ, 3, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.dockWidgetContents_11)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem17)
        self.dockJoint.setWidget(self.dockWidgetContents_11)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockJoint)
        self.dockScene = QtGui.QDockWidget(MainWindow)
        self.dockScene.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockScene.setObjectName("dockScene")
        self.dockWidgetContents_12 = QtGui.QWidget()
        self.dockWidgetContents_12.setObjectName("dockWidgetContents_12")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_20 = QtGui.QLabel(self.dockWidgetContents_12)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_5.addWidget(self.label_20)
        self.projection = QtGui.QComboBox(self.dockWidgetContents_12)
        self.projection.setObjectName("projection")
        self.projection.addItem("")
        self.projection.addItem("")
        self.horizontalLayout_5.addWidget(self.projection)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem18)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.useCallLists = QtGui.QCheckBox(self.dockWidgetContents_12)
        self.useCallLists.setChecked(True)
        self.useCallLists.setObjectName("useCallLists")
        self.verticalLayout_4.addWidget(self.useCallLists)
        self.line_12 = QtGui.QFrame(self.dockWidgetContents_12)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_4.addWidget(self.line_12)
        self.automateNextStep = QtGui.QPushButton(self.dockWidgetContents_12)
        self.automateNextStep.setObjectName("automateNextStep")
        self.verticalLayout_4.addWidget(self.automateNextStep)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem19)
        self.dockScene.setWidget(self.dockWidgetContents_12)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockScene)
        self.dockSlice = QtGui.QDockWidget(MainWindow)
        self.dockSlice.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockSlice.setObjectName("dockSlice")
        self.dockWidgetContents_13 = QtGui.QWidget()
        self.dockWidgetContents_13.setObjectName("dockWidgetContents_13")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents_13)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_21 = QtGui.QLabel(self.dockWidgetContents_13)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_6.addWidget(self.label_21)
        self.spinBox100AxisSlice = QtGui.QSpinBox(self.dockWidgetContents_13)
        self.spinBox100AxisSlice.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.spinBox100AxisSlice.setObjectName("spinBox100AxisSlice")
        self.horizontalLayout_6.addWidget(self.spinBox100AxisSlice)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.slider100AxisSlice = QtGui.QSlider(self.dockWidgetContents_13)
        self.slider100AxisSlice.setOrientation(QtCore.Qt.Horizontal)
        self.slider100AxisSlice.setObjectName("slider100AxisSlice")
        self.verticalLayout_3.addWidget(self.slider100AxisSlice)
        self.line_13 = QtGui.QFrame(self.dockWidgetContents_13)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_3.addWidget(self.line_13)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_61 = QtGui.QLabel(self.dockWidgetContents_13)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_7.addWidget(self.label_61)
        self.spinBox010AxisSlice = QtGui.QSpinBox(self.dockWidgetContents_13)
        self.spinBox010AxisSlice.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.spinBox010AxisSlice.setObjectName("spinBox010AxisSlice")
        self.horizontalLayout_7.addWidget(self.spinBox010AxisSlice)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.slider010AxisSlice = QtGui.QSlider(self.dockWidgetContents_13)
        self.slider010AxisSlice.setOrientation(QtCore.Qt.Horizontal)
        self.slider010AxisSlice.setObjectName("slider010AxisSlice")
        self.verticalLayout_3.addWidget(self.slider010AxisSlice)
        self.line_14 = QtGui.QFrame(self.dockWidgetContents_13)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_3.addWidget(self.line_14)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_62 = QtGui.QLabel(self.dockWidgetContents_13)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_9.addWidget(self.label_62)
        self.spinBox001AxisSlice = QtGui.QSpinBox(self.dockWidgetContents_13)
        self.spinBox001AxisSlice.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.spinBox001AxisSlice.setObjectName("spinBox001AxisSlice")
        self.horizontalLayout_9.addWidget(self.spinBox001AxisSlice)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.slider001AxisSlice = QtGui.QSlider(self.dockWidgetContents_13)
        self.slider001AxisSlice.setOrientation(QtCore.Qt.Horizontal)
        self.slider001AxisSlice.setObjectName("slider001AxisSlice")
        self.verticalLayout_3.addWidget(self.slider001AxisSlice)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem20)
        self.dockSlice.setWidget(self.dockWidgetContents_13)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockSlice)
        self.dockTol = QtGui.QDockWidget(MainWindow)
        self.dockTol.setObjectName("dockTol")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_65 = QtGui.QLabel(self.dockWidgetContents)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_10.addWidget(self.label_65)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_54 = QtGui.QLabel(self.dockWidgetContents)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.gridLayout_5.addWidget(self.label_54, 0, 0, 1, 1)
        self.label_63 = QtGui.QLabel(self.dockWidgetContents)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.gridLayout_5.addWidget(self.label_63, 0, 1, 1, 1)
        self.label_64 = QtGui.QLabel(self.dockWidgetContents)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayout_5.addWidget(self.label_64, 0, 2, 1, 1)
        self.tolVecXOrigin = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.tolVecXOrigin.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.tolVecXOrigin.setDecimals(4)
        self.tolVecXOrigin.setMinimum(-1000000.0)
        self.tolVecXOrigin.setMaximum(1000000.0)
        self.tolVecXOrigin.setObjectName("tolVecXOrigin")
        self.gridLayout_5.addWidget(self.tolVecXOrigin, 1, 0, 1, 1)
        self.tolVecYOrigin = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.tolVecYOrigin.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.tolVecYOrigin.setDecimals(4)
        self.tolVecYOrigin.setMinimum(-1000000.0)
        self.tolVecYOrigin.setMaximum(1000000.0)
        self.tolVecYOrigin.setObjectName("tolVecYOrigin")
        self.gridLayout_5.addWidget(self.tolVecYOrigin, 1, 1, 1, 1)
        self.tolVecZOrigin = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.tolVecZOrigin.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.tolVecZOrigin.setDecimals(4)
        self.tolVecZOrigin.setMinimum(-1000000.0)
        self.tolVecZOrigin.setMaximum(1000000.0)
        self.tolVecZOrigin.setObjectName("tolVecZOrigin")
        self.gridLayout_5.addWidget(self.tolVecZOrigin, 1, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_5)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_66 = QtGui.QLabel(self.dockWidgetContents)
        self.label_66.setObjectName("label_66")
        self.gridLayout_16.addWidget(self.label_66, 0, 1, 1, 1)
        self.tolVecLength = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.tolVecLength.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.tolVecLength.setMaximum(1000.0)
        self.tolVecLength.setSingleStep(5.0)
        self.tolVecLength.setProperty("value", 10.0)
        self.tolVecLength.setObjectName("tolVecLength")
        self.gridLayout_16.addWidget(self.tolVecLength, 0, 2, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem21, 0, 0, 1, 1)
        self.label_69 = QtGui.QLabel(self.dockWidgetContents)
        self.label_69.setObjectName("label_69")
        self.gridLayout_16.addWidget(self.label_69, 1, 1, 1, 1)
        self.tolVecAngle = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.tolVecAngle.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.tolVecAngle.setMaximum(180.0)
        self.tolVecAngle.setSingleStep(5.0)
        self.tolVecAngle.setProperty("value", 45.0)
        self.tolVecAngle.setObjectName("tolVecAngle")
        self.gridLayout_16.addWidget(self.tolVecAngle, 1, 2, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_16)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.xAxisLabel_2 = QtGui.QLabel(self.dockWidgetContents)
        self.xAxisLabel_2.setObjectName("xAxisLabel_2")
        self.gridLayout_15.addWidget(self.xAxisLabel_2, 1, 0, 1, 1)
        self.label_67 = QtGui.QLabel(self.dockWidgetContents)
        self.label_67.setObjectName("label_67")
        self.gridLayout_15.addWidget(self.label_67, 0, 0, 1, 1)
        self.tolXRotSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.tolXRotSpinBox.setEnabled(True)
        self.tolXRotSpinBox.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.tolXRotSpinBox.setMinimum(-90.0)
        self.tolXRotSpinBox.setMaximum(90.0)
        self.tolXRotSpinBox.setSingleStep(15.0)
        self.tolXRotSpinBox.setObjectName("tolXRotSpinBox")
        self.gridLayout_15.addWidget(self.tolXRotSpinBox, 1, 2, 1, 1)
        self.label_68 = QtGui.QLabel(self.dockWidgetContents)
        self.label_68.setObjectName("label_68")
        self.gridLayout_15.addWidget(self.label_68, 0, 2, 1, 1)
        self.zAxisLabel_2 = QtGui.QLabel(self.dockWidgetContents)
        self.zAxisLabel_2.setObjectName("zAxisLabel_2")
        self.gridLayout_15.addWidget(self.zAxisLabel_2, 3, 0, 1, 1)
        self.yAxisLabel_2 = QtGui.QLabel(self.dockWidgetContents)
        self.yAxisLabel_2.setObjectName("yAxisLabel_2")
        self.gridLayout_15.addWidget(self.yAxisLabel_2, 2, 0, 1, 1)
        self.tolYRotSlider = QtGui.QSlider(self.dockWidgetContents)
        self.tolYRotSlider.setEnabled(True)
        self.tolYRotSlider.setMaximum(360)
        self.tolYRotSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tolYRotSlider.setObjectName("tolYRotSlider")
        self.gridLayout_15.addWidget(self.tolYRotSlider, 2, 1, 1, 1)
        self.tolZRotSlider = QtGui.QSlider(self.dockWidgetContents)
        self.tolZRotSlider.setEnabled(True)
        self.tolZRotSlider.setMaximum(360)
        self.tolZRotSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tolZRotSlider.setObjectName("tolZRotSlider")
        self.gridLayout_15.addWidget(self.tolZRotSlider, 3, 1, 1, 1)
        self.tolYRotSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.tolYRotSpinBox.setEnabled(True)
        self.tolYRotSpinBox.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.tolYRotSpinBox.setMaximum(360.0)
        self.tolYRotSpinBox.setSingleStep(15.0)
        self.tolYRotSpinBox.setObjectName("tolYRotSpinBox")
        self.gridLayout_15.addWidget(self.tolYRotSpinBox, 2, 2, 1, 1)
        self.tolZRotSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.tolZRotSpinBox.setEnabled(True)
        self.tolZRotSpinBox.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.tolZRotSpinBox.setMaximum(360.0)
        self.tolZRotSpinBox.setSingleStep(15.0)
        self.tolZRotSpinBox.setObjectName("tolZRotSpinBox")
        self.gridLayout_15.addWidget(self.tolZRotSpinBox, 3, 2, 1, 1)
        self.tolXRotSlider = QtGui.QSlider(self.dockWidgetContents)
        self.tolXRotSlider.setEnabled(True)
        self.tolXRotSlider.setMinimum(0)
        self.tolXRotSlider.setMaximum(360)
        self.tolXRotSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tolXRotSlider.setObjectName("tolXRotSlider")
        self.gridLayout_15.addWidget(self.tolXRotSlider, 1, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_15)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_70 = QtGui.QLabel(self.dockWidgetContents)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.verticalLayout_12.addWidget(self.label_70)
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_71 = QtGui.QLabel(self.dockWidgetContents)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.gridLayout_17.addWidget(self.label_71, 0, 0, 1, 1)
        self.label_72 = QtGui.QLabel(self.dockWidgetContents)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout_17.addWidget(self.label_72, 0, 1, 1, 1)
        self.label_73 = QtGui.QLabel(self.dockWidgetContents)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.gridLayout_17.addWidget(self.label_73, 0, 2, 1, 1)
        self.tolVecX = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.tolVecX.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.tolVecX.setReadOnly(True)
        self.tolVecX.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.tolVecX.setDecimals(4)
        self.tolVecX.setMinimum(-1000000.0)
        self.tolVecX.setMaximum(1000000.0)
        self.tolVecX.setObjectName("tolVecX")
        self.gridLayout_17.addWidget(self.tolVecX, 1, 0, 1, 1)
        self.tolVecY = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.tolVecY.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.tolVecY.setReadOnly(True)
        self.tolVecY.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.tolVecY.setDecimals(4)
        self.tolVecY.setMinimum(-1000000.0)
        self.tolVecY.setMaximum(1000000.0)
        self.tolVecY.setObjectName("tolVecY")
        self.gridLayout_17.addWidget(self.tolVecY, 1, 1, 1, 1)
        self.tolVecZ = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.tolVecZ.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.tolVecZ.setReadOnly(True)
        self.tolVecZ.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.tolVecZ.setDecimals(4)
        self.tolVecZ.setMinimum(-1000000.0)
        self.tolVecZ.setMaximum(1000000.0)
        self.tolVecZ.setObjectName("tolVecZ")
        self.gridLayout_17.addWidget(self.tolVecZ, 1, 2, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_17)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem22)
        self.dockTol.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockTol)

        self.retranslateUi(MainWindow)
        self.viewTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Joint Test", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Set View:", None, QtGui.QApplication.UnicodeUTF8))
        self.setView.setItemText(1, QtGui.QApplication.translate("MainWindow", "front", None, QtGui.QApplication.UnicodeUTF8))
        self.setView.setItemText(2, QtGui.QApplication.translate("MainWindow", "back", None, QtGui.QApplication.UnicodeUTF8))
        self.setView.setItemText(3, QtGui.QApplication.translate("MainWindow", "top", None, QtGui.QApplication.UnicodeUTF8))
        self.setView.setItemText(4, QtGui.QApplication.translate("MainWindow", "bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.setView.setItemText(5, QtGui.QApplication.translate("MainWindow", "left", None, QtGui.QApplication.UnicodeUTF8))
        self.setView.setItemText(6, QtGui.QApplication.translate("MainWindow", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.setView.setItemText(7, QtGui.QApplication.translate("MainWindow", "ortho1", None, QtGui.QApplication.UnicodeUTF8))
        self.setView.setItemText(8, QtGui.QApplication.translate("MainWindow", "ortho2", None, QtGui.QApplication.UnicodeUTF8))
        self.setView.setItemText(9, QtGui.QApplication.translate("MainWindow", "ortho3", None, QtGui.QApplication.UnicodeUTF8))
        self.setView.setItemText(10, QtGui.QApplication.translate("MainWindow", "ortho4", None, QtGui.QApplication.UnicodeUTF8))
        self.setView.setItemText(11, QtGui.QApplication.translate("MainWindow", "ortho5", None, QtGui.QApplication.UnicodeUTF8))
        self.setView.setItemText(12, QtGui.QApplication.translate("MainWindow", "ortho6", None, QtGui.QApplication.UnicodeUTF8))
        self.setView.setItemText(13, QtGui.QApplication.translate("MainWindow", "ortho7", None, QtGui.QApplication.UnicodeUTF8))
        self.setView.setItemText(14, QtGui.QApplication.translate("MainWindow", "ortho8", None, QtGui.QApplication.UnicodeUTF8))
        self.automate.setText(QtGui.QApplication.translate("MainWindow", "Automate", None, QtGui.QApplication.UnicodeUTF8))
        self.loadModel.setText(QtGui.QApplication.translate("MainWindow", "Load Model", None, QtGui.QApplication.UnicodeUTF8))
        self.loadAtlas.setText(QtGui.QApplication.translate("MainWindow", "Load Atlas", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultScene.setText(QtGui.QApplication.translate("MainWindow", "Load Default Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.clearScene.setText(QtGui.QApplication.translate("MainWindow", "Clear Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.GrabScreen.setText(QtGui.QApplication.translate("MainWindow", "Screen Grab", None, QtGui.QApplication.UnicodeUTF8))
        self.viewTabs.setTabText(self.viewTabs.indexOf(self.openGlTab), QtGui.QApplication.translate("MainWindow", "3D View", None, QtGui.QApplication.UnicodeUTF8))
        self.label_74.setText(QtGui.QApplication.translate("MainWindow", "Uptake of Radiotracer per Bone Region", None, QtGui.QApplication.UnicodeUTF8))
        self.copyTable.setText(QtGui.QApplication.translate("MainWindow", "Copy Table", None, QtGui.QApplication.UnicodeUTF8))
        self.saveCSV.setText(QtGui.QApplication.translate("MainWindow", "Save CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.viewTabs.setTabText(self.viewTabs.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Nuclear Medicine Breakdown", None, QtGui.QApplication.UnicodeUTF8))
        self.dockItemList.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Scene Items List", None, QtGui.QApplication.UnicodeUTF8))
        self.dockCamera.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.camUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "CameraPosition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "Look At", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "Up Vector", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("MainWindow", "Orientation Quaternion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("MainWindow", "W", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.dockLights.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lights", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Light Number", None, QtGui.QApplication.UnicodeUTF8))
        self.lightEnable.setText(QtGui.QApplication.translate("MainWindow", "Light Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Diffuse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Emissive", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Specular", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Ambient", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Light\n"
"Position", None, QtGui.QApplication.UnicodeUTF8))
        self.directionalLight.setText(QtGui.QApplication.translate("MainWindow", "Directional Light", None, QtGui.QApplication.UnicodeUTF8))
        self.dockModel.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.modelVisible.setText(QtGui.QApplication.translate("MainWindow", "Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.enableColorDrivenModelsCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Enable Color Driven Models", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Diffuse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Emissive", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Specular", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Ambient", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Shiny", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Not Shiny", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Shininess", None, QtGui.QApplication.UnicodeUTF8))
        self.invertNormals.setText(QtGui.QApplication.translate("MainWindow", "Invert Normals", None, QtGui.QApplication.UnicodeUTF8))
        self.saveModel.setText(QtGui.QApplication.translate("MainWindow", "Save Model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(QtGui.QApplication.translate("MainWindow", "Point Size", None, QtGui.QApplication.UnicodeUTF8))
        self.dockJoint.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Joint", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Rotation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Order", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationOrder.setItemText(0, QtGui.QApplication.translate("MainWindow", "xyz", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationOrder.setItemText(1, QtGui.QApplication.translate("MainWindow", "xzy", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationOrder.setItemText(2, QtGui.QApplication.translate("MainWindow", "yxz", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationOrder.setItemText(3, QtGui.QApplication.translate("MainWindow", "yzx", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationOrder.setItemText(4, QtGui.QApplication.translate("MainWindow", "zxy", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationOrder.setItemText(5, QtGui.QApplication.translate("MainWindow", "zyx", None, QtGui.QApplication.UnicodeUTF8))
        self.sphericalCoord.setText(QtGui.QApplication.translate("MainWindow", "Spherical coordinates", None, QtGui.QApplication.UnicodeUTF8))
        self.xAxisLabel.setText(QtGui.QApplication.translate("MainWindow", "Elevation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.zAxisLabel.setText(QtGui.QApplication.translate("MainWindow", "Spin", None, QtGui.QApplication.UnicodeUTF8))
        self.yAxisLabel.setText(QtGui.QApplication.translate("MainWindow", "Azimuth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("MainWindow", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.jointXPosStep.setText(QtGui.QApplication.translate("MainWindow", "Step X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Step Size", None, QtGui.QApplication.UnicodeUTF8))
        self.jointYPosStep.setText(QtGui.QApplication.translate("MainWindow", "Step Y", None, QtGui.QApplication.UnicodeUTF8))
        self.jointZPosStep.setText(QtGui.QApplication.translate("MainWindow", "Step Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Orientation Quaternion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "W", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.dockScene.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Projection", None, QtGui.QApplication.UnicodeUTF8))
        self.projection.setItemText(0, QtGui.QApplication.translate("MainWindow", "Perspective", None, QtGui.QApplication.UnicodeUTF8))
        self.projection.setItemText(1, QtGui.QApplication.translate("MainWindow", "Orthographic", None, QtGui.QApplication.UnicodeUTF8))
        self.useCallLists.setText(QtGui.QApplication.translate("MainWindow", "Use Call Lists", None, QtGui.QApplication.UnicodeUTF8))
        self.automateNextStep.setText(QtGui.QApplication.translate("MainWindow", "Next Step", None, QtGui.QApplication.UnicodeUTF8))
        self.dockSlice.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Slice View Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "[1,0,0] Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("MainWindow", "[0,1,0] Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("MainWindow", "[0,0,1] Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.dockTol.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tolerance Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setText(QtGui.QApplication.translate("MainWindow", "Vector Origin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("MainWindow", "Vector Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("MainWindow", "Angle Tolerence", None, QtGui.QApplication.UnicodeUTF8))
        self.xAxisLabel_2.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("MainWindow", "Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("MainWindow", "Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.zAxisLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.yAxisLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("MainWindow", "Vector", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
